export { default as Button } from "./Button";
export { default as InputForm} from "./InpForm";
export { default as SearchItem} from "./SearchItem";
export { default as Province} from "./Province";
export { default as ProvinceBtn} from "./ProvinceBtn";
export { default as Item} from "./Item";
export { default as ItemSidebar} from "./ItemSidebar";
export { default as Intro} from "./Intro";
export { default as Contact} from "./Contact";
export { default as Slider} from "./Slider";
export { default as BoxInfo} from "./BoxInfo";
export { default as RelatedPost} from "./RelatedPost";
export { default as Sitem} from "./Sitem";
