const actionTypes = {
    LOGIN:'LOGIN',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAIL:'REGISTER_FAIL',
    LOGOUT:'LOGOUT',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    GET_POSTS:"GET_POSTS",
    GET_POST_LIMIT:"GET_POST_LIMIT",

    GET_CATEGORIES:"GET_CATEGORIES",
    GET_CURRENT:'GET_CURRENT',
    GET_PRICES : 'GET_PRICES',
    GET_AREAS : 'GET_AREAS',
}

export default actionTypes;